# Generated by Django 5.2.5 on 2025-08-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_alter_milage_car_alter_milage_moto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milage',
            name='milage',
            field=models.PositiveBigIntegerField(verbose_name='Пробег'),
        ),
    ]
